name: sorah-rbpkg/actions
description: Setup sorah-ruby, see also https://github.com/sorah-rbpkg/ruby.
inputs:
  ruby-version:
    description: Ruby version, for example `2.7`, `3.0`, `3.1` or `3.2``.
    required: false
  ruby-version-file:
    description: Ruby version file, for example `.ruby-version`.
    required: false
  bundler-cache:
    description: Cache bundler gems and run `bundle install` automatically.
    required: false
    default: "false"
runs:
  using: "node16"
  main: "dist/index.js"
